Repository ikaros-dev/ikaros, pull requests merged in 2022-12, with the labels that each got.

#130 fix get option network dto issue
  src/main/java/run/ikaros/server/service/OptionServiceImpl.java
Labels: bug

#131 Update deploy doc
  .run/IkarosDev.run.xml
  .run/IkarosLocal.run.xml
  .run/IkarosPro.run.xml
  .run/JellfyinLocalOnce.run.xml
  .run/MariadbLocalOnce.run.xml
  .run/QbittorrentLocalOnce.run.xml
  docs/deploy/deploy-with-docker-compose.md
  docs/deploy/deploy-with-docker-run.md
  docs/deploy/docker-compose-no-jellyfin.yml
  docs/deploy/docker-compose.yml
Labels: documentation

#132 impl qbittorrent webapi auth by cookies, close #128
  CHANGELOG.MD
  docs/deploy/deploy-with-docker-compose.md
  docs/deploy/deploy-with-docker-run.md
  src/main/java/run/ikaros/server/constants/DefaultConst.java
  src/main/java/run/ikaros/server/core/service/OptionService.java
  src/main/java/run/ikaros/server/event/QbittorrentOptionUpdateEvent.java
  src/main/java/run/ikaros/server/listener/QbittorrentOptionUpdateEventListener.java
  src/main/java/run/ikaros/server/model/dto/OptionQbittorrentDTO.java
  src/main/java/run/ikaros/server/service/OptionServiceImpl.java
  src/main/java/run/ikaros/server/tripartite/qbittorrent/QbittorrentClient.java
Labels: bug

#133 Switch db postgresql
  BUILD.MD
  CHANGELOG.MD
  README.MD
  build.gradle
  config/example/resource/application-dev.yaml
  config/example/resource/application-local.yaml
  docs/deploy/deploy-with-docker-compose.md
  docs/deploy/deploy-with-docker-run.md
  docs/deploy/docker-compose-no-jellyfin.yml
  docs/deploy/docker-compose.yml
  src/main/java/run/ikaros/server/entity/AnimeEntity.java
  src/main/java/run/ikaros/server/entity/BaseEntity.java
  src/main/java/run/ikaros/server/entity/EpisodeEntity.java
  src/main/java/run/ikaros/server/entity/OptionEntity.java
  src/main/java/run/ikaros/server/entity/SeasonEntity.java
  src/main/java/run/ikaros/server/entity/UserEntity.java
  src/main/java/run/ikaros/server/service/FileServiceImpl.java
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: feature

#134 fix checkstyle code issue
  src/main/java/run/ikaros/server/entity/AnimeEntity.java
  src/main/java/run/ikaros/server/entity/BaseEntity.java
  src/main/java/run/ikaros/server/entity/EpisodeEntity.java
  src/main/java/run/ikaros/server/entity/OptionEntity.java
  src/main/java/run/ikaros/server/entity/SeasonEntity.java
  src/main/java/run/ikaros/server/entity/UserEntity.java
  src/main/java/run/ikaros/server/service/FileServiceImpl.java
Labels: bug

#138 [Documentation] 添加微信公众号信息
  CHANGELOG.MD
  README.MD
Labels: documentation

#145 143 feature anime sub resource download
  CHANGELOG.MD
  gradle.properties
  src/main/java/run/ikaros/server/config/TaskManagerConfig.java
  src/main/java/run/ikaros/server/core/repository/UserSubscribeRepository.java
  src/main/java/run/ikaros/server/core/service/TaskService.java
  src/main/java/run/ikaros/server/core/service/UserService.java
  src/main/java/run/ikaros/server/core/service/UserSubscribeService.java
  src/main/java/run/ikaros/server/openapi/TaskRestController.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/main/java/run/ikaros/server/service/UserService.java
  src/main/java/run/ikaros/server/service/UserSubscribeServiceImpl.java
  src/main/resources/admin/css/816.8903803c.css
  src/main/resources/admin/index.html
  src/main/resources/admin/js/31.249dc362.js
  src/main/resources/admin/js/816.5063ecd9.js
  src/main/resources/admin/js/app.65883001.js
  src/main/resources/admin/js/app.c0b37552.js
  src/test/java/run/ikaros/server/service/TaskServiceTest.java
Labels: feature

#146 fix dockerfile build issue
  Dockerfile
  build.gradle
Labels: bug

#156 publish first test version
  .github/workflows/ikaros_ci_build_dev_container.yml
  .github/workflows/ikaros_ci_build_tag_container.yml
  CHANGELOG.MD
  README.MD
  docs/deploy/docker-compose-no-jellyfin.yml
  docs/deploy/docker-compose.yml
  gradle.properties
Labels: documentation

#163 161 feature add logo
  CHANGELOG.MD
  README.MD
  assets/logo.png
  src/main/resources/admin/img/logo.69b9dfed.png
  src/main/resources/admin/index.html
  src/main/resources/admin/js/963.9c8a4108.js
  src/main/resources/admin/js/963.ceaae293.js
  src/main/resources/admin/js/app.a1da9b12.js
  src/main/resources/admin/js/app.d4e5ed93.js
Labels: feature

#165 add filter for issue that generate media dir when anime entity status…
  src/main/java/run/ikaros/server/service/MediaServiceImpl.java
Labels: bug

#168 fix NotifyService not init bean issue
  src/main/java/run/ikaros/server/service/NotifyServiceImpl.java
Labels: bug

#174 remove cover url in mail content for 544 issue
  src/main/java/run/ikaros/server/listener/EpisodeUrlUpdateEventListener.java
  src/main/resources/templates/mail/anime_update.html
Labels: feature

#179 Fix issue that notify notify can't have jp content and parse mikan rss fail
  CHANGELOG.MD
  src/main/java/run/ikaros/server/listener/EpisodeUrlUpdateEventListener.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/main/resources/templates/mail/anime_update.html
Labels: bug

#181 optimize episode url update notify
  CHANGELOG.MD
  src/main/java/run/ikaros/server/core/service/SeasonService.java
  src/main/java/run/ikaros/server/event/EpisodeUrlUpdateEvent.java
  src/main/java/run/ikaros/server/listener/EpisodeUrlUpdateEventListener.java
  src/main/java/run/ikaros/server/params/SeasonMatchingEpParams.java
  src/main/java/run/ikaros/server/service/EpisodeServiceImpl.java
  src/main/java/run/ikaros/server/service/SeasonServiceImpl.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
Labels: feature

#187 Optimize mail content and server file hard link
  CHANGELOG.MD
  docs/deploy/deploy-with-docker-compose.md
  docs/deploy/docker-compose-no-jellyfin.yml
  docs/deploy/docker-compose.yml
  src/main/java/run/ikaros/server/event/EpisodeUrlUpdateEvent.java
  src/main/java/run/ikaros/server/listener/EpisodeUrlUpdateEventListener.java
  src/main/java/run/ikaros/server/prop/IkarosProperties.java
  src/main/java/run/ikaros/server/service/SeasonServiceImpl.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/main/resources/application.yaml
  src/main/resources/templates/mail/anime_update.html
  src/test/java/run/ikaros/server/thymeleaf/TemplateEngineTest.java
Labels: bug, feature

#189 fix mail cover img url issue
  CHANGELOG.MD
  src/main/java/run/ikaros/server/listener/EpisodeUrlUpdateEventListener.java
  src/main/java/run/ikaros/server/service/SeasonServiceImpl.java
  src/test/java/run/ikaros/server/lang/StringTest.java
Labels: bug

#192 fix episodes matching files fail issue
  CHANGELOG.MD
  src/main/java/run/ikaros/server/service/SeasonServiceImpl.java
Labels: bug

#194 add subtitle hard link generate in media dir
  CHANGELOG.MD
  src/main/java/run/ikaros/server/core/repository/FileRepository.java
  src/main/java/run/ikaros/server/core/service/FileService.java
  src/main/java/run/ikaros/server/service/FileServiceImpl.java
  src/main/java/run/ikaros/server/service/MediaServiceImpl.java
Labels: bug, feature

#200 fix rss service null pointer exception when download rss subscrible fail
  src/main/java/run/ikaros/server/service/RssServiceImpl.java
Labels: bug

#205 fix bug #136 that matching fail when episode file name has year such as 2022
  CHANGELOG.MD
  src/main/java/run/ikaros/server/constants/RegexConst.java
  src/main/java/run/ikaros/server/utils/RegexUtils.java
  src/test/java/run/ikaros/server/constants/RegexConstTest.java
  src/test/java/run/ikaros/server/utils/RegexUtilsTest.java
Labels: bug

#211 update readme.md that change video list url
  README.MD
Labels: documentation

#214 fix original dir generate issue
  CHANGELOG.MD
  src/main/java/run/ikaros/server/service/MediaServiceImpl.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/main/java/run/ikaros/server/utils/FileUtils.java
Labels: bug

#217 Fix mail send issue
  CHANGELOG.MD
  config/example/resource/application-local.yaml
  src/main/java/run/ikaros/server/service/NotifyServiceImpl.java
Labels: bug

#219 Optimize server upload hard link
  CHANGELOG.MD
  src/main/java/run/ikaros/server/constants/FileConst.java
  src/main/java/run/ikaros/server/entity/FileEntity.java
  src/main/java/run/ikaros/server/service/FileServiceImpl.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/test/java/run/ikaros/server/service/SeasonServiceTest.java
Labels: bug, feature

#220 add logic that check file hard link after app start
  CHANGELOG.MD
  src/main/java/run/ikaros/server/IkarosApplication.java
  src/main/java/run/ikaros/server/constants/AppConst.java
  src/main/java/run/ikaros/server/exceptions/CheckFailException.java
  src/main/java/run/ikaros/server/utils/FileUtils.java
Labels: feature

#223 Refactor Docker image
  CHANGELOG.MD
  Dockerfile
  entrypoint.sh
Labels: feature

#226 fix issue #225 that dockerfile build image cant not start normally
  CHANGELOG.MD
  Dockerfile
  entrypoint.sh
Labels: bug

#229 Update Dockerfile
  Dockerfile
Labels: bug

#231 optimize torrent matching season episode
  CHANGELOG.MD
  src/main/java/run/ikaros/server/core/service/MikanService.java
  src/main/java/run/ikaros/server/core/service/TaskService.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/main/java/run/ikaros/server/tripartite/mikan/service/MikanServiceImpl.java
  src/test/java/run/ikaros/server/service/impl/MikanServiceImplTest.java
Labels: bug

#235 fix dockerfile issue #234
  CHANGELOG.MD
  Dockerfile
  config/script/entrypoint.sh
Labels: bug

#232 use springdoc as open api component
  CHANGELOG.MD
  build.gradle
  src/main/java/run/ikaros/server/config/SwaggerConfig.java
  src/main/java/run/ikaros/server/openapi/AnimeRestController.java
  src/main/java/run/ikaros/server/openapi/EpisodeRestController.java
  src/main/java/run/ikaros/server/openapi/FileRestController.java
  src/main/java/run/ikaros/server/openapi/MetadataRestController.java
  src/main/java/run/ikaros/server/openapi/NetworkRestController.java
  src/main/java/run/ikaros/server/openapi/NotifyRestController.java
  src/main/java/run/ikaros/server/openapi/OptionRestController.java
  src/main/java/run/ikaros/server/openapi/SeasonRestController.java
  src/main/java/run/ikaros/server/openapi/SongRestController.java
  src/main/java/run/ikaros/server/openapi/StatusRestController.java
  src/main/java/run/ikaros/server/openapi/TaskRestController.java
  src/main/java/run/ikaros/server/openapi/TorrentRestController.java
  src/main/java/run/ikaros/server/openapi/TripartiteRestController.java
  src/main/java/run/ikaros/server/openapi/UserRestController.java
  src/main/resources/application.yaml
  src/test/java/run/ikaros/server/service/RssServiceTest.java
Labels: bug, documentation

#237 fix issue #236 that logic incorrect
  src/main/java/run/ikaros/server/core/tripartite/bgmtv/constants/BgmTvConst.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
Labels: bug

#242 Optimize db entities
  CHANGELOG.MD
  docs/design/Design4Version1.0.0.drawio
  src/main/java/run/ikaros/server/constants/DefaultConst.java
  src/main/java/run/ikaros/server/core/repository/SubscribeRepository.java
  src/main/java/run/ikaros/server/core/repository/UserSubscribeRepository.java
  src/main/java/run/ikaros/server/core/service/OptionService.java
  src/main/java/run/ikaros/server/core/service/SubscribeService.java
  src/main/java/run/ikaros/server/core/service/UserSubscribeService.java
  src/main/java/run/ikaros/server/entity/SubscribeEntity.java
  src/main/java/run/ikaros/server/entity/UserSubscribeEntity.java
  src/main/java/run/ikaros/server/enums/OptionSeo.java
  src/main/java/run/ikaros/server/listener/EpisodeUrlUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/OptionBgmTvEnableProxyUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/OptionBgmTvTokenUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/OptionMikanEnableProxyUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/OptionNetworkUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/OptionNotifyUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/QbittorrentOptionUpdateEventListener.java
  src/main/java/run/ikaros/server/listener/SubscribeBgmTvSubjectEventListener.java
  src/main/java/run/ikaros/server/model/dto/AnimeDTO.java
  src/main/java/run/ikaros/server/model/dto/OptionBgmTvDTO.java
  src/main/java/run/ikaros/server/openapi/UserRestController.java
  src/main/java/run/ikaros/server/service/AnimeServiceImpl.java
  src/main/java/run/ikaros/server/service/OptionServiceImpl.java
  src/main/java/run/ikaros/server/service/SeasonServiceImpl.java
  src/main/java/run/ikaros/server/service/SubscribeServiceImpl.java
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
  src/main/java/run/ikaros/server/service/UserSubscribeServiceImpl.java
  src/main/java/run/ikaros/server/tripartite/bgmtv/repository/BgmTvRepositoryImpl.java
  src/main/java/run/ikaros/server/tripartite/bgmtv/service/BgmTvServiceImpl.java
Labels: feature

#243 use flyway for db table
  .gitignore
  CHANGELOG.MD
  build.gradle
  gradle.properties
  src/main/java/run/ikaros/server/entity/BaseEntity.java
  src/main/java/run/ikaros/server/tripartite/bgmtv/service/BgmTvServiceImpl.java
  src/main/resources/application.yaml
  src/main/resources/migration/V0.1.0_0001__DDL_User.sql
  src/main/resources/migration/V0.1.0_0002__DDL_Options.sql
  src/main/resources/migration/V0.1.0_0003__DDL_File.sql
  src/main/resources/migration/V0.1.0_0004__DDL_Album.sql
  src/main/resources/migration/V0.1.0_0005__DDL_Anime.sql
  src/main/resources/migration/V0.1.0_0006__DDL_Episode.sql
  src/main/resources/migration/V0.1.0_0007__DDL_KeyValue.sql
  src/main/resources/migration/V0.1.0_0008__DDL_Season.sql
  src/main/resources/migration/V0.1.0_0009__DDL_Song.sql
  src/main/resources/migration/V0.1.0_0010__DDL_SongMenu.sql
  src/main/resources/migration/V0.1.0_0011__DDL_Subscribe.sql
  src/main/resources/migration/V0.1.0_0012__DDL_Task.sql
Labels: feature

#246 fix issue #245
  CHANGELOG.MD
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
Labels: bug

#251 Update docker-compose example & Optimize the number of image layers
  Dockerfile
  docs/deploy/docker-compose-no-jellyfin.yml
  docs/deploy/docker-compose.yml
Labels: documentation

#263 fix bug #259 that save qbittorrent option need to long time
  .gitignore
  CHANGELOG.MD
  src/main/java/run/ikaros/server/config/AsyncConfig.java
  src/main/java/run/ikaros/server/core/service/NotifyService.java
  src/main/java/run/ikaros/server/core/service/OptionService.java
  src/main/java/run/ikaros/server/listener/QbittorrentOptionUpdateEventListener.java
  src/main/java/run/ikaros/server/openapi/OptionRestController.java
  src/main/java/run/ikaros/server/service/OptionServiceImpl.java
  src/main/java/run/ikaros/server/tripartite/qbittorrent/QbittorrentClient.java
Labels: bug

#266 optimize matching episode after scan qbittorrent has downloaded finish torrent file
  CHANGELOG.MD
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
Labels: feature

#267 optimize matching logic in TaskService#updateEpisodeUrlByFileEntity
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
Labels: bug

#268 optimize log print for matching fail in TaskServiceImpl#updateEpisodeUrlByFileEntity
  src/main/java/run/ikaros/server/service/TaskServiceImpl.java
Labels: feature

#269 Update README.MD
  README.MD
Labels: documentation

#271 update readme.md that add rfc repo
  CHANGELOG.MD
  README.MD
  gradle.properties
Labels: documentation
